"""Download endpoints for RTL files, reports, PCB files"""
from fastapi import APIRouter, HTTPException
from fastapi.responses import Response
import os

router = APIRouter()

# Store design data temporarily (will be populated by chat endpoint)
session_designs = {}

def save_session_design(session_id: str, design_data: dict):
    """Save design data for downloads"""
    session_designs[session_id] = design_data

@router.get("/download/rtl/{session_id}")
async def download_rtl(session_id: str):
    """Download RTL Verilog code"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    rtl_code = design.get("rtl_code", "// No RTL code available")
    
    return Response(
        content=rtl_code,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=rtl_{session_id[:8]}.v"}
    )

@router.get("/download/testbench/{session_id}")
async def download_testbench(session_id: str):
    """Download testbench code"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    testbench = design.get("testbench", "// No testbench available")
    
    return Response(
        content=testbench,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=testbench_{session_id[:8]}.v"}
    )

@router.get("/download/report/{session_id}")
async def download_report(session_id: str):
    """Download design report"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    parsed_spec = design.get("parsed_spec", {})
    architecture = design.get("architecture", {})
    simulation = design.get("simulation", {})
    
    # Generate report
    report = f"""# HARDWARE DESIGN REPORT
# Session: {session_id}

## COMPONENT SPECIFICATION
- Component: {parsed_spec.get('component', 'N/A')}
- Bit Width: {parsed_spec.get('bit_width', 'N/A')}
- Operations: {', '.join(parsed_spec.get('operations', []))}

## ARCHITECTURE
- Module Name: {architecture.get('module_name', 'N/A')}
- Inputs: {', '.join([p['name'] for p in architecture.get('ports', {}).get('inputs', [])])}
- Outputs: {', '.join([p['name'] for p in architecture.get('ports', {}).get('outputs', [])])}

## ESTIMATED METRICS
- Area: {architecture.get('estimated_metrics', {}).get('area_mm2', 'N/A')} mm²
- Power: {architecture.get('estimated_metrics', {}).get('power_mw', 'N/A')} mW
- Max Frequency: {architecture.get('estimated_metrics', {}).get('max_freq_mhz', 'N/A')} MHz
- Latency: {architecture.get('estimated_metrics', {}).get('latency_ns', 'N/A')} ns

## SIMULATION RESULTS
- Status: {simulation.get('status', 'N/A')}
- Test Cases: {simulation.get('test_count', 0)}
- Passed: {simulation.get('passed', 0)}
- Failed: {simulation.get('failed', 0)}

## FILES GENERATED
- RTL Code: /download/rtl/{session_id}
- Testbench: /download/testbench/{session_id}
- Report: This file

---
Generated by SPARTA Hardware Design Assistant v2.0
"""
    
    return Response(
        content=report,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=report_{session_id[:8]}.txt"}
    )

@router.get("/download/pcb/schematic/{session_id}")
async def download_pcb_schematic(session_id: str):
    """Download PCB schematic as text file"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    pcb_design = design.get("pcb_design", {})
    schematic = pcb_design.get("schematic", "No schematic available")
    
    return Response(
        content=schematic,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=schematic_{session_id[:8]}.txt"}
    )

@router.get("/download/pcb/bom/{session_id}")
async def download_pcb_bom(session_id: str):
    """Download BOM as CSV"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    pcb_design = design.get("pcb_design", {})
    bom = pcb_design.get("bom", [])
    
    # Generate CSV
    csv_lines = ["Component,Value,Package,Quantity,Price"]
    for item in bom:
        csv_lines.append(
            f"{item.get('component', 'N/A')},{item.get('value', 'N/A')},"
            f"{item.get('package', 'N/A')},{item.get('qty', 1)},${item.get('price', '0.00')}"
        )
    
    bom_csv = "\\n".join(csv_lines)
    
    return Response(
        content=bom_csv,
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=bom_{session_id[:8]}.csv"}
    )

@router.get("/download/pcb/gerber/{session_id}")
async def download_gerber_info(session_id: str):
    """Download Gerber file information as text"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    pcb_design = design.get("pcb_design", {})
    gerber = pcb_design.get("gerber_files", {})
    
    # Generate Gerber file listing
    gerber_info = f"""# Gerber Files for PCB Manufacturing
# Session: {session_id}

## Files Included:
"""
    for layer, filename in gerber.items():
        gerber_info += f"- {layer}: {filename}\\n"
    
    gerber_info += f"""
## Board Specifications:
- Size: {pcb_design.get('board_size', {}).get('width', 100)}mm x {pcb_design.get('board_size', {}).get('height', 80)}mm
- Layers: {pcb_design.get('layers', 2)}
- Trace Width: {pcb_design.get('trace_width', '0.25mm')}
- Clearance: {pcb_design.get('clearance', '0.2mm')}

## Manufacturing Notes:
Send these files to your PCB manufacturer (JLCPCB, PCBWay, etc.)
"""
    
    return Response(
        content=gerber_info,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=gerber_info_{session_id[:8]}.txt"}
    )

@router.get("/download/pcb/layout/{session_id}")
async def download_pcb_layout(session_id: str):
    """Download PCB layout information as text"""
    if session_id not in session_designs:
        raise HTTPException(status_code=404, detail="Design not found")
    
    design = session_designs[session_id]
    pcb_design = design.get("pcb_design", {})
    layout = pcb_design.get("layout", {})
    
    layout_info = f"""# PCB Layout Information
# Session: {session_id}

## Board Specifications:
- Outline: {layout.get('board_outline', 'N/A')}
- Layers: {layout.get('layers', 'N/A')}
- Via Count: {layout.get('via_count', 0)}
- Mounting Holes: {layout.get('mounting_holes', 0)}

## Routing Details:
- Trace Routing: {layout.get('trace_routing', 'N/A')}
- Ground Plane: {layout.get('ground_plane', 'N/A')}
- Power Plane: {layout.get('power_plane', 'N/A')}

## Component Placement:
- Strategy: {layout.get('component_placement', 'N/A')}
- Silkscreen: {layout.get('silkscreen', 'N/A')}
"""
    
    return Response(
        content=layout_info,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=layout_{session_id[:8]}.txt"}
    )
